/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdom;

import java.io.*; 
import org.jdom.*; 
import org.jdom.input.*; 
import org.jdom.filter.*; 
import java.util.List; 
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdom.parc.document;
import static jdom.parc.racine;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.jdom.xpath.XPath;

public class formul extends javax.swing.JFrame {
    static Element racine=new Element("FILMS");
    static org.jdom.Document document =new Document(racine);
    //Element film= new Element("FILM");
    Element film;
    Element roles;
    int R=0;
    String fichier="C:/Users/mouns/Desktop/Films.xml";
    String fichier2="C:/Users/mouns/Desktop/Films2.xml";
  
    public formul()    {
        try {
            initComponents();
            setLocation(460,80);
            System.out.print("**********");
            jCombolistartist.addItem("selectioner l'artiste");   
            SAXBuilder sxb =  new SAXBuilder();
            document = sxb.build(new File(fichier));
            racine=document.getRootElement();
            List listart =  racine.getChildren("ARTISTE");
            Iterator i =  listart.iterator();
            
            while(i.hasNext())
            {
                Element courant =  (Element)i.next();
                jCombolistartist.addItem(courant.getAttributeValue("id").toString()); 
                //jCombolistartist.addItem(courant.getAttributeValue("id").toString()+" .. "+courant.getChild("ACTNOM").getText());
            }   
        } catch (JDOMException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jB_add_clonage = new javax.swing.JButton();
        jB_add_creation = new javax.swing.JButton();
        jB_enregistrer = new javax.swing.JButton();
        jtext_titre = new javax.swing.JTextField();
        jtext_genre = new javax.swing.JTextField();
        jtext_pays = new javax.swing.JTextField();
        jLabeltitre = new javax.swing.JLabel();
        jLabelgenre = new javax.swing.JLabel();
        jLabelpays = new javax.swing.JLabel();
        jLabelroles = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelresume = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArearesumer = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jB_addrole = new javax.swing.JButton();
        jTextNom = new javax.swing.JTextField();
        jTextprenom = new javax.swing.JTextField();
        jTextintitule = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCombolistartist = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_add_clonage.setText("ajouter mode clonage");
        jB_add_clonage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_add_clonageActionPerformed(evt);
            }
        });

        jB_add_creation.setText("ajouter mode creation");
        jB_add_creation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_add_creationActionPerformed(evt);
            }
        });

        jB_enregistrer.setText("enregister");
        jB_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_enregistrerActionPerformed(evt);
            }
        });

        jtext_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_titreActionPerformed(evt);
            }
        });

        jLabeltitre.setText("TITRE");

        jLabelgenre.setText("GENRE");

        jLabelpays.setText("PAYS");

        jLabelroles.setText("ROLE");

        jLabel1.setText("ARTISTE");

        jLabelresume.setText("RESUME");

        jTextArearesumer.setColumns(20);
        jTextArearesumer.setRows(5);
        jScrollPane1.setViewportView(jTextArearesumer);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("2-interface");
        jLabel2.setMaximumSize(new java.awt.Dimension(86, 16));

        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jB_addrole.setText("ajouter roles");
        jB_addrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addroleActionPerformed(evt);
            }
        });

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        jLabel3.setText("NOM :");

        jLabel4.setText("PRENOM :");

        jLabel5.setText("INTITULE :");

        jCombolistartist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombolistartistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelpays))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelgenre)
                                            .addComponent(jLabeltitre))
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtext_pays, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jtext_genre)
                                    .addComponent(jtext_titre)
                                    .addComponent(jCombolistartist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jB_add_clonage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_add_creation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabelresume))
                            .addComponent(jLabelroles, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextprenom, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextNom)
                                    .addComponent(jTextintitule))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_addrole))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 235, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtext_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeltitre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtext_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelgenre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtext_pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpays))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCombolistartist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelroles)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextintitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jB_addrole))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelresume))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jB_add_clonage)
                        .addGap(18, 18, 18)
                        .addComponent(jB_add_creation)
                        .addGap(18, 18, 18)
                        .addComponent(jB_enregistrer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jB_add_clonageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_add_clonageActionPerformed
        
        try {
            SAXBuilder builder = new SAXBuilder();
            document = builder.build(new File(fichier));
            racine = document.getRootElement();
            System.out.println(racine.toString());
           //1 element
            Element film = (Element) racine.getChildren().get(1);
            System.out.println("film cloner 1 :"+film.getValue());
            racine.addContent((Element) film.clone());
            //2 element
            Element film2 = (Element) racine.getChildren().get(8);
            //System.out.println("type de class :"+film2.getContent().toString().getClass());
            System.out.println("film cloner 2 :"+film2.getValue());
            racine.addContent((Element) film2.clone());
            JOptionPane.showMessageDialog(null, "CLONAGE EST TERMINER");
        } catch (JDOMException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
    }//GEN-LAST:event_jB_add_clonageActionPerformed

    private void jB_add_creationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_add_creationActionPerformed
        
        // *************element film ****************
        R=0;
        film= new Element("FILM");
       // racine.addContent(film);
        Attribute annee =  new Attribute("Annee","1998"); 
        film.setAttribute(annee);        
        //*************element titre**************
        Element titre =  new Element("TITRE");
        titre.setText(jtext_titre.getText().toString());
        film.addContent(titre);
        //**************element genre************
        Element genre =  new Element("GENRE");
        genre.setText(jtext_genre.getText().toString());
        film.addContent(genre);
        //element pays
        Element pays =  new Element("PAYS");
        pays.setText(jtext_pays.getText().toString());
        film.addContent(pays);
        //****************artiste avec xpath************
        /*try {
            String textartist = jTextArtiste.getText();
            XPath a = XPath.newInstance("//ARTISTE[@id="+textartist+"]/@id");
        } catch (JDOMException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        //*************element artist ***************
       
        Element mes =new Element("MES");
        Attribute idref =  new Attribute("idref",jCombolistartist.getSelectedItem().toString());
        mes.setAttribute(idref);
        film.addContent(mes);
        //resume
       
        Element resume =  new Element("RESUME");
        resume.setText(jTextArearesumer.getText().toString());
        film.addContent(resume);
        //ajouter roles
        //roles=new Element("ROLES");   
        film.addContent(roles);
        //créer film
        racine.addContent(film);
        //vider formulaire
        jtext_titre.setText("");
        jtext_genre.setText("");
        jtext_pays.setText("");
        jTextArearesumer.setText("");
        
        JOptionPane.showMessageDialog(null, "film creer");
        
    }//GEN-LAST:event_jB_add_creationActionPerformed
   
    private void jtext_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_titreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_titreActionPerformed

    private void jB_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_enregistrerActionPerformed
        
        XMLOutputter sortie =  new XMLOutputter(Format.getPrettyFormat());  
        try {
            sortie.output(document, new FileOutputStream(fichier2));
           JOptionPane.showMessageDialog(null, "fichier2 est bien enregistrer");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formul.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jB_enregistrerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parc p=new parc();
       p.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB_addroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addroleActionPerformed
        
//roles=new Element("ROLES");
    if(R==0)
    {
        roles=new Element("ROLES");
    }
        Element role=new Element("ROLE");
        Element prenom=new Element("PRENOM");
        Element nom=new Element("NOM");
        Element intitule=new Element("INTITULE");
        prenom.setText(jTextNom.getText().toString());
        nom.setText(jTextprenom.getText().toString());
        intitule.setText(jTextintitule.getText().toString());
        role.addContent(prenom);
        role.addContent(nom);
        role.addContent(intitule);
        roles.addContent(role);
        R=1;
        //film.addContent(roles);
        JOptionPane.showMessageDialog(null, "roles creer");
        jTextNom.setText("");
        jTextprenom.setText("");    
        jTextintitule.setText("");
    }//GEN-LAST:event_jB_addroleActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jCombolistartistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombolistartistActionPerformed
        
    }//GEN-LAST:event_jCombolistartistActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_add_clonage;
    private javax.swing.JButton jB_add_creation;
    private javax.swing.JButton jB_addrole;
    private javax.swing.JButton jB_enregistrer;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombolistartist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelgenre;
    private javax.swing.JLabel jLabelpays;
    private javax.swing.JLabel jLabelresume;
    private javax.swing.JLabel jLabelroles;
    private javax.swing.JLabel jLabeltitre;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArearesumer;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextintitule;
    private javax.swing.JTextField jTextprenom;
    private javax.swing.JTextField jtext_genre;
    private javax.swing.JTextField jtext_pays;
    private javax.swing.JTextField jtext_titre;
    // End of variables declaration//GEN-END:variables
}
